project:
  type: website
  output-dir: "docs"
  render:
    - index.qmd
    - BLR_lab_*.qmd
    - Assignments/**/*.qmd
    - "!lectures_2526/**"

website:
  title: "Beyond MLR"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Labs week 1"
        menu:
          - text: "Lab 1"
            href: BLR_lab_FE_oneway.qmd
          - text: "Lab 2"
            href: BLR_lab_randomized_block.qmd
      - text: "Labs week 2"
        menu:
          - text: "Lab 3"
            href: BLR_lab_two_way_factorial.qmd
          - text: "Lab 4"
            href: BLR_lab_replicated_randomized_block.qmd      
      - text: "Assignments"
        menu:
          - text: "Week 1"
            href: Assignments/Week 1/Assignment_week_1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
